[package]
name = "villagekit-math"
version.workspace = true
edition.workspace = true

[dependencies]
villagekit-unit = { path = "../unit" }
villagekit-number = { path = "../number" }
glam.workspace = true
serde.workspace = true

[dev-dependencies]
villagekit-unit = { path = "../unit" }
