[package]
name = "villagekit-unit"
version.workspace = true
edition.workspace = true

[dependencies]
villagekit-number = { path = "../number" }
serde.workspace = true
num-traits.workspace = true
shrewnit = { git = "https://github.com/Gavin-Niederman/shrewnit" }
