[package]
name = "villagekit-product"
version.workspace = true
edition.workspace = true

[dependencies]
villagekit-render = { path = "../render" }
villagekit-unit = { path = "../unit" }
bevy_ecs = "0.15.3"
