[package]
name = "villagekit-demo"
version.workspace = true
edition.workspace = true

[dependencies]
villagekit-engine = { path = "../engine", version = "0.1.0" }
bevy = { version = "0.15.0", features = ["dynamic_linking"] }
serde_json = "1.0.134"
uuid = "1.11.0"
